server:
  port: 8080
  servlet:
    context-path: /piano
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/**,classpath:/public/
    application:
      name: piano

myenvironment:
  name: 开发环境
